# Numpy

In [1]:
import numpy as np

#creating a 2 dimensional (3,2) array

In [5]:
arr = [1,2],[3,4],[5,6] 
a = np.array(arr)         

In [6]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


#adding to an array

In [7]:
b = a + 3.2

In [8]:
print(b)

[[4.2 5.2]
 [6.2 7.2]
 [8.2 9.2]]


#creating (3,2) ones array

In [12]:
size = (3,2)
arr1 = np.ones(size)

In [13]:
print(arr1)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


#dot product of 2 arrays

In [16]:
x = [1,2],[2,3]
y = [3,4],[4,5]

In [17]:
dotProduct = np.dot(x,y)

In [18]:
print(dotProduct)

[[11 14]
 [18 23]]


#slicing the first row from dotProduct

In [38]:
firstRow = dotProduct[:1]

In [39]:
print(firstRow)

[[11 14]]


#summin the first row

In [41]:
rowSum = np.sum(firstRow)

In [42]:
print(rowSum)

25
